export const FETCH_SONGS_REQUEST = 'FETCH_SONGS_REQUEST'
export const FETCH_SONGS_SUCCESS = 'FETCH_SONGS_SUCCESS'
export const FETCH_SONGS_FAILURE = 'FETCH_SONGS_FAILURE'

export const ADD_SONG_REQUEST = 'ADD_SONG_REQUEST'
export const ADD_SONG_SUCCESS = 'ADD_SONG_SUCCESS'
export const ADD_SONG_FAILURE = 'ADD_SONG_FAILURE'
